### ISSUE TITLE
`install_version` does not work for `type != source`

### ISSUE THREAD

**Issue by FelixErnst** [r-lib/remotes#513] opened 2020-06-20 14:54 UTC
Hi,

`install_version` does not work for `type` values other than `source`. I looked at the man page, but there is no explanation for this as well. It states:

> type	
> character, indicating the type of package to download and install. Will be "source" except on Windows and some macOS builds: see the section on ‘Binary packages’ for those.

I looked at the source code and there is not comment explaining, why the `type` argument even exists, if it is hard coded to `source`.

Thanks for any explanation on this topic.

Felix

<details><summary>Session info</summary>
<pre>> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] drat_0.1.6.1   compiler_4.0.0 tools_4.0.0    remotes_2.1.1  git2r_0.27.1  </pre>
</details>

**Comment by FelixErnst** [comment] 2020-06-27 11:55
bump, @gaborcsardi @jimhester

**Comment by jimhester** [comment] 2020-06-29 12:22
Because `install_version()` is used for installing packages from the CRAN archive, and the CRAN archive stores only source packages, not binaries.

**Comment by jimhester** [comment] 2020-06-29 12:23
This is a duplicate of https://github.com/r-lib/remotes/issues/307, so closing

**Closed by jimhester** 2020-06-29 12:23 UTC

**Comment by FelixErnst** [comment] 2020-06-29 19:50
Thanks for the info. Didn't know that.
