### ISSUE TITLE
Unexpected interaction between GITHUB_PAT and CRAN-like repo

### ISSUE THREAD

**Issue by copernican** [r-lib/remotes#481] opened 2020-02-28 18:14 UTC
An [Artifactory repo](https://www.jfrog.com/confluence/display/JFROG/CRAN+Repositories) can be used to host internally developed R packages. Packages can be installed with a command like
```r
install.packages("foo", repos = "https://our.repo/"
```
To install a specific version of `foo` from this repo, I tried
```r
install_version("foo", "x.y.z")
```
but this fails with a 401 error. This seems to be related to whether `GITHUB_PAT` is set. I've edited the below reprex to sanitize the internal repo and package details.
``` r
remotes::install_version("foo", "x.y.z", upgrade = "never")
#> Downloading package from url: https://our.repo/src/contrib/foo_x.y.z.tar.gz
#> Error: Failed to install 'unknown package' from URL:
#>   HTTP error 401.
#>   Bad credentials
#> 
#>   Rate limit remaining: 47/60
#>   Rate limit reset at: 2020-02-28 18:40:55 UTC
#> 
#> 
Sys.unsetenv("GITHUB_PAT")
remotes::install_version("foo", "x.y.z", upgrade = "never")
#> Downloading package from url: https://our.repo/src/contrib/foo_x.y.z.tar.gz
#> Installing package into '/usr/local/lib/R/3.6/site-library'
#> (as 'lib' is unspecified)
```
I'm using `remotes` 2.1.1.

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment] 2020-04-03 20:52
This seems like a duplicate of https://github.com/r-lib/remotes/issues/440

**Closed by jimhester** 2020-04-03 20:52 UTC
