### ISSUE TITLE
`remotes::system_requirements`: ` Error: JSON: EXPECTED value GOT < `

### ISSUE THREAD

**Issue by bschilder** [r-lib/remotes#663] opened 2021-10-29 14:50 UTC
Running:
```R
remotes::system_requirements("ubuntu", "20.04")
```
produces the following error as of today:
```
 Error: JSON: EXPECTED value GOT < 
```
### Expected output

Character vector of Ubuntu system requirements.

### Recurring issue

#494 
#324

Many thanks, 
Brian

**Comment by jimhester** [comment] 2021-10-29 18:15
I can't reproduce this, and this error simply occurs when the endpoint returns HTML or XML instead of JSON, likely due to an error page. What package you were you trying to retrieve the system requirements for?

**Comment by bschilder** [comment] 2021-10-29 20:52
> I can't reproduce this, and this error simply occurs when the endpoint returns HTML or XML instead of JSON, likely due to an error page.

I think that's the crux of the issue, it happens seemingly at random. 

Some things that might help:  

1. When the function encounters this error, have it rerun another N times to see if succeeds. 
2. Provide an error message indicating it was a problem with the endpoint (eg perhaps due to connection issues? issues with the server it's querying?) as opposed to the user misusing the function. This will help the user to narrow down the potential source of the error right away.

> What package you were you trying to retrieve the system requirements for?

In this particular case, I'm using this function to install the necessary Linux deps to build and test my R packages (in this case `orthogene`). You can see an example here:
https://github.com/neurogenomics/orthogene/runs/4049835231?check_suite_focus=true

However, several hours ago, this error was also occurring when I ran the function by itself within my local Rstudio (MacOS), so it seems pretty independent of the pipeline

**Comment by dinakar29** [comment] 2021-12-02 13:03
I think this issue occurs due to [public RSPM](https://packagemanager.rstudio.com/client/#/) being unavailable at random times, as it is now. 

![image](https://user-images.githubusercontent.com/26552821/144427169-618a3079-da93-4e6c-8648-0e273ce4ac3c.png)

**Comment by dinakar29** [comment] 2021-12-02 13:07
The status page says RSPM is operational though... Must be a bug

![image](https://user-images.githubusercontent.com/26552821/144427604-a6f61e1e-26e6-4612-a645-5af6839bc1f1.png)

**Comment by mpadge** [comment] 2021-12-02 14:23
This issue has also currently disabled rOpenSci's review bot, which is unable to check packages. Can reproduce by running call in a clean `rocker/tidyverse` container. A prompt fix would be very much appreciated :smile: :+1:

**Comment by mpadge** [comment] 2021-12-02 15:59
Hmm, all seems okay again now. It is clearly intermittent as @dinakar29 suggested, but during times of failure it does seem entirely reproducible.

**Comment by dinakar29** [comment] 2021-12-17 15:03
Caught this in action, again:
![image](https://user-images.githubusercontent.com/26552821/146564255-dbc1f295-eb86-44a3-b004-e52758d4cc4d.png)

At least the status page reports the outage this time:
![image](https://user-images.githubusercontent.com/26552821/146564161-c2c47e49-c616-4fa4-a599-a1cb99d37177.png)

Hopefully RStudio has any plans to improve stability/resiliency/HA for public-facing RSPM, as the demand for it grows over time.

**Comment by gaborcsardi** [comment] 2021-12-17 15:16
We have plans both to improve the performance, and also to have better fallback, but both will take a couple of weeks unfortunately.

**Comment by gaborcsardi** [comment] 2023-11-01 14:22
Hopefully this has been fixed now.

**Closed by gaborcsardi** 2023-11-01 14:22 UTC
