### ISSUE TITLE
Submodules doesn't work (example from readme broken)

### ISSUE THREAD

**Issue by pommedeterresautee** [r-lib/remotes#407] opened 2019-07-26 08:49 UTC
I tried the XGBoost example from the readme file:
`remotes::install_github("dmlc/xgboost/R-package")`
Got an error (an include missing):
```
> remotes::install_github("dmlc/xgboost/R-package")
Downloading GitHub repo dmlc/xgboost@master
✔  checking for file ‘/tmp/Rtmpt4cPtd/remotes4b6e7aebabab/dmlc-xgboost-9b9e298/R-package/DESCRIPTION’ ...
─  preparing ‘xgboost’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘xgboost_1.0.0.1.tar.gz’
   
Installing package into ‘/home/geantvert/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘xgboost’ ...
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
Makevars:17: -DRABIT_STRICT_CXX98_
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../..//include -I../..//dmlc-core/include -I../..//rabit/include -I../../ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -fopenmp -pthread -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-el7SHG/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c xgboost_R.cc -o xgboost_R.o
xgboost_R.cc:2:10: fatal error: dmlc/logging.h: Aucun fichier ou dossier de ce type
 #include <dmlc/logging.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:169: xgboost_R.o] Error 1
ERROR: compilation failed for package ‘xgboost’
* removing ‘/home/geantvert/R/x86_64-pc-linux-gnu-library/3.5/xgboost’
* restoring previous ‘/home/geantvert/R/x86_64-pc-linux-gnu-library/3.5/xgboost’
Erreur : Failed to install 'xgboost' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/Rtmpt4cPtd/file4b6e137ee6c8/xgboost_1.0.0.1.tar.gz’ had non-zero exit status
```
The file not found is in a submodule of the project.
According to the remotes package doc, submodules are supported, which is quite strange.
I get the very same error on MacOs and on Ubuntu 19.04, both having a git client installed.

**Comment by pommedeterresautee** [comment] 2019-07-26 13:18
I think that I have identified the source of the bug:

It happens there:
```R
  source <- source_pkg(bundle, subdir = remote$subdir)
  on.exit(unlink(source, recursive = TRUE), add = TRUE)

  update_submodules(source, quiet)
```
`source` variable contains the path to the R-package (which in our case is a subdir in the repo), but `.gitmodules` file is in the root path of the repo. So `update_submodules()` function doesn't find it!

There are 2 obvious ways to fix it:
- generate the path where to decompress the zip before calling `source_pkg()` so we know the path when calling `update_submodules()`
- rewrite path from `source` variable to let it do the stuff (easier but the way the package works seems quite tricky)

@gaborcsardi @jimhester have you a preference? (I can commit something if you think it s doable without having to guess all the tricks to avoid)

**Comment by jimhester** [comment] 2019-07-26 13:34
Closing, as this is a duplicate of https://github.com/r-lib/remotes/issues/233

**Closed by jimhester** 2019-07-26 13:34 UTC

**Comment by pommedeterresautee** [comment] 2019-07-26 15:38
oups sorry for the duplicate
