### ISSUE TITLE
devtools::install_github() and devtools::check() succeed under Linux but fail under Windows

### ISSUE THREAD

**Issue by sgutreuter** [r-lib/remotes#680] opened 2021-12-14 17:37 UTC
I have an R package for which devtools:check() shows no errors, warnings or notes, and it installs and runs as expected under Linux Mint.
However, devtools:check() fails under Windows, as does devtools::install_github().  However, install_packages() pointing to a clone of the repo on the Windows box succeeds.

Reproducible code, including the results of traceback() and sessionInfo() is attached.

[devtools_errors.txt](https://github.com/r-lib/remotes/files/7713601/devtools_errors.txt)

**Comment by gaborcsardi** [comment] 2021-12-14 18:03
I cannot reproduce this. Do you have a custom user-level Makevars file?

```
R> devtools::install_github("sgutreuter/screenr", ref = "master")
Downloading GitHub repo sgutreuter/screenr@master
Error: Failed to install 'screenr' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE
R> traceback()
10: stop(remote_install_error(remotes[[i]], e))
9: value[[3L]](cond)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
5: install_remotes(remotes, auth_token = auth_token, host = host,
       dependencies = dependencies, upgrade = upgrade, force = force,
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual,
       build_vignettes = build_vignettes, repos = repos, type = type,
       ...)
4: force(code)
3: withr::with_path(rtools_path(), code)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action",
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir,
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host,
               dependencies = dependencies, upgrade = upgrade, force = force,
               quiet = quiet, build = build, build_opts = build_opts,
               build_manual = build_manual, build_vignettes = build_vignettes,
               repos = rep os, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github("sgutreuter/screenr", ref = "master")
```

**Comment by gaborcsardi** [comment] 2023-11-01 14:22
Closing for lack of information. Please reopen with more info if you still have this problem. Thanks!

**Closed by gaborcsardi** 2023-11-01 14:22 UTC
