### ISSUE TITLE
`remotes::install_bitbucket`: devtools-divergent error

### ISSUE THREAD

**Issue by r-cheologist** [r-lib/remotes#230] opened 2018-10-29 11:29 UTC
The following code block works with `devtools` (1.13.6):

    ReportR_module_packages <- c(
      "ReporteR.base",
      "ReporteR.sampleprep",
      "ReporteR.autonomics")
    
    ## Fix a problem with 'subdir' path creation
    if(pacman::p_version('remotes') <= as.package_version('2.0.1'))
    {
      ReportR_module_packages <- paste0(ReportR_module_packages, '/')
    }
    
    for(pk in ReportR_module_packages)
    {
      devtools::install_bitbucket(
        repo = "graumannlabtools/ReporteR",
        subdir = pk,
        upgrade_dependencies = TRUE)
      # remotes::install_bitbucket(
      #   repo   = "graumannlabtools/ReporteR",
      #   subdir =  pk,
      #   upgrade = 'always')
    }

But if switching the `for`-loop-wrapped code to the commented out equivalent from `remotes` (2.0.1), I get the following error at `ReportR_module_packages[3]`:

    Error in vapply(remotes, install_remote, ..., FUN.VALUE = character(1)) : 
    values must be type 'character', but FUN(X[[1]]) result is type 'logical'

**Comment by jimhester** [comment] 2018-10-29 17:59
I cannot reproduce this error, can you be sure to use the devel version of remotes and make sure to restart your R session before installing with remotes.

**Comment by gaborcsardi** [comment] 2019-01-19 15:48
FWIW with latest remotes (a0d6cd5d52062fcaedac7dd19b03f9211f578791) I get
```
Downloading bitbucket repo graumannlabtools/ReporteR@master
Error in FUN(X[[i]], ...) : is.remote(remote) is not TRUE
```

**Comment by jimhester** [comment] 2019-06-20 14:16
This seems fixed now (though you get an error due to pathological being archived on CRAN).

**Closed by jimhester** 2019-06-20 14:16 UTC
