### ISSUE TITLE
install_github() not installing contents of 'inst' folder

### ISSUE THREAD

**Issue by profandyfield** [r-lib/remotes#161] opened 2018-09-18 19:13 UTC
I have a package of r tutorials written in learnr ([adventr](https://github.com/profandyfield/adventr)) that I deploy through github.
In case you're not familiar with learnr, each tutorial sits in its own folder within a folder called tutorials in the 'inst' folder of the package. For example, the tutorial called 'adventr_01' sits in inst > tutorials > adventr_01

When you install, the tutorials folder should be installed within the top level of the package (as with any folder within inst). This is what happens using install_github("profandyfield/adventr") on my personal mac and laptop (and indeed others who I know use then package). However, I recently stumbled across an issue when trying to install this package on my university teaching computers (Windows 10). These computers have a desktop install of RStudio, but packages are installed in the user directory, not the usual `C:/PROGRA~1/R/.....` directory. For example, here's what I get when I try to install my package using install_github:

`
> install_github("profandyfield/adventr")
Downloading GitHub repo profandyfield/adventr@master
from URL https://api.github.com/repos/profandyfield/adventr/zipball/master
Installing adventr
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file  \
--no-environ --no-save --no-restore --quiet CMD INSTALL  \
"C:/Users/andyf/AppData/Local/Temp/RtmpS6jYMY/devtools206c7ba031a6/profandyfield-adventr-ed315c1"  \
--library="\\its-home.uscs.susx.ac.uk/home/andyf/Documents/R/win-library/3.5"  \
`

None of the above seems odd, and that's what happens when packages are installed from CRAN. When I look in `Documents/R/win-library/3.5` I see a folder with my adventr package as expected BUT the contents of the `inst` folder are not there. In other words, the install appears fine at face value except that there is no `tutorials` folder in the package folder - the contents of 'inst' have not been copied to `Documents/R/win-library/3.5/adventr` as they should be.

When I try to run a tutorial I get an error that it doesn't exist (obviously, because it doesn't). it seems to me it might be a problem resulting from the library being created in a location other than the default. Is this a remotes issue or a me being stupid issue? Is there any obvious reason why the 'inst' folder is being ignored at install? Apologies if this is a dumb question - I'm fairly new to packages and stuff ... Thanks very much for any suggestions you have.

**Comment by gaborcsardi** [comment] 2018-09-18 20:53
I cannot reproduce this. I would try removing the package folder and running the installation again. After  it is done you can use `system.file(package = "adventr")` to see the directory of the installed package, and `dir(system.file(package = "adventr"))` to see the files in the package directory. This  contains `tutorials` for me.

**Comment by profandyfield** [comment] 2018-09-19 08:37
Thanks for getting back to me. I've done the above, and it still installs but without the tutorials folder. Here's the full install message:

```
> remotes::install_github("profandyfield/adventr")
Downloading GitHub repo profandyfield/adventr@master
Installing 1 packages: reprex
package ‘reprex’ successfully unpacked and MD5 sums checked
Installing package into ‘\\its-home.uscs.susx.ac.uk/home/andyf/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
'\\its-home.uscs.susx.ac.uk\home\andyf\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'adventr' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: package 'learnr' was built under R version 3.5.1
Warning: package 'tidyverse' was built under R version 3.5.1
Warning: package 'ggplot2' was built under R version 3.5.1
Warning: package 'tibble' was built under R version 3.5.1
Warning: package 'tidyr' was built under R version 3.5.1
Warning: package 'readr' was built under R version 3.5.1
Warning: package 'purrr' was built under R version 3.5.1
Warning: package 'dplyr' was built under R version 3.5.1
Warning: package 'stringr' was built under R version 3.5.1
Warning: package 'forcats' was built under R version 3.5.1
** help
*** installing help indices
  converting help for package 'adventr'
    finding HTML links ... done
    adventr                                 html  
    alice_dat                               html  
    calcite_dat                             html  
    garlic_dat                              html  
    ha_dat                                  html  
    implant_dat                             html  
    jig_dat                                 html  
    mask_dat                                html  
    mem_cov_dat                             html  
    memory_dat                              html  
    ras_dat                                 html  
    recovery_dat                            html  
    rehab_dat                               html  
    rehab_growth_dat                        html  
    taser_dat                               html  
    teddy_dat                               html  
    zhang_female_dat                        html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Warning: package 'learnr' was built under R version 3.5.1
Warning: package 'tidyverse' was built under R version 3.5.1
Warning: package 'ggplot2' was built under R version 3.5.1
Warning: package 'tibble' was built under R version 3.5.1
Warning: package 'tidyr' was built under R version 3.5.1
Warning: package 'readr' was built under R version 3.5.1
Warning: package 'purrr' was built under R version 3.5.1
Warning: package 'dplyr' was built under R version 3.5.1
Warning: package 'stringr' was built under R version 3.5.1
Warning: package 'forcats' was built under R version 3.5.1
*** arch - x64
Warning: package 'learnr' was built under R version 3.5.1
Warning: package 'tidyverse' was built under R version 3.5.1
Warning: package 'ggplot2' was built under R version 3.5.1
Warning: package 'tibble' was built under R version 3.5.1
Warning: package 'tidyr' was built under R version 3.5.1
Warning: package 'readr' was built under R version 3.5.1
Warning: package 'purrr' was built under R version 3.5.1
Warning: package 'dplyr' was built under R version 3.5.1
Warning: package 'stringr' was built under R version 3.5.1
Warning: package 'forcats' was built under R version 3.5.1
* DONE (adventr)
In R CMD INSTALL
```

Our university desktop install is running R 3.5.0 (hence the warnings) but otherwise it looks fine. The package is found where it is supposed to be:

```
> system.file(package = "adventr")
[1] "\\\\its-home.uscs.susx.ac.uk/home/andyf/Documents/R/win-library/3.5/adventr"
```
but the tutorial folder is missing:
```
> dir(system.file(package = "adventr"))
[1] "data"        "DESCRIPTION" "help"        "html"       
[5] "INDEX"       "Meta"        "NAMESPACE"   "R"     
```
I will check again with our ITS people to see whether there's any reason at this end why that folder would be prevented from installing. I realise if you can't reproduce the error it's almost impossible for you to suggest anything, but if you have any further thoughts I'd be grateful.

**Comment by gaborcsardi** [comment] 2018-09-19 08:41
I am afraid that this fails because of the UNC path, and this is actually an  `install.packages()` issue, remotes just calls that for the actual installation.

Also, what version of remotes is this? Can you please try the current GitHub version, just in case it is not caused by the UNC path, but something else.

**Comment by profandyfield** [comment] 2018-09-19 08:51
Thanks. I've just tried with the GitHub release of remotes, same problem. Is there a workaround for the UNC path issue that you know of or could point me towards?

**Comment by gaborcsardi** [comment] 2018-09-19 08:56
You can map the UNC path to a drive letter:  https://www.howtogeek.com/118452/how-to-map-network-drives-from-the-command-prompt-in-windows/

**Comment by profandyfield** [comment] 2018-09-19 09:09
Thanks - I've found some related stuff by searching, and it looks like the issue was raised [here](https://github.com/r-lib/devtools/issues/1230) too. I'll talk to our system admins and hope they have a solution! Thanks so much for your help - knowing what the problem is is a huge step forwards. Thank you.

**Comment by gaborcsardi** [comment] 2018-09-19 09:10
Well, I am not sure it is the UNC path, maybe.

**Comment by profandyfield** [comment] 2018-09-19 09:59
Just to close the loop on this, turns out the network share is already mapped, and adventr installs correctly by specifying the lib explicitly:

```
remotes::install_github("profandyfield/adventr", lib = "N:/Documents/R/win-library/3.5")
```
phew. Thanks again - I'm really grateful.

**Comment by gaborcsardi** [comment] 2018-09-19 10:01
Great, thanks for letting me know! It is good to know about this issue, we'll see if we can fix it in r-lib/pkginstall. Since it will not be fixed in remotes, I'll close it now.

**Closed by gaborcsardi** 2018-09-19 10:01 UTC
