### ISSUE TITLE
Tricky-to-debug error message when installing stplanr

### ISSUE THREAD

**Issue by Robinlovelace** [r-lib/remotes#318] opened 2019-03-21 07:36 UTC
I'm a happy user of `remotes` and have recently switched from `devtools::install*()` to `remotes::install*()` to keep up with the times. It's an awesome pkg and usually works 100% of the time for me. However, I'm bamboozled by this error message that has cropped up and I have no idea how to debug (it does not affect other computers I'm working on). And ideas?:

``` r
remotes::install_local("~/repos/stplanr/", force = TRUE)
#> Error in FUN(X[[i]], ...): is.remote(remote) is not TRUE
traceback()
#> No traceback available
```

<sup>Created on 2019-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Ubuntu 18.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2019-03-21                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                        
#>  assertthat    0.2.0      2017-04-11 [1] standard (@0.2.0)             
#>  backports     1.1.3      2018-12-14 [2] CRAN (R 3.5.1)                
#>  callr         3.2.0      2019-03-15 [2] CRAN (R 3.5.3)                
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                
#>  crayon        1.3.4      2017-09-16 [1] standard (@1.3.4)             
#>  desc          1.2.0      2018-05-01 [2] CRAN (R 3.5.0)                
#>  devtools      2.0.1      2018-10-26 [2] CRAN (R 3.5.1)                
#>  digest        0.6.18     2018-10-10 [2] CRAN (R 3.5.1)                
#>  evaluate      0.13       2019-02-12 [2] CRAN (R 3.5.2)                
#>  fs            1.2.6      2018-08-23 [2] CRAN (R 3.5.1)                
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                
#>  highr         0.7        2018-06-09 [2] CRAN (R 3.5.0)                
#>  htmltools     0.3.6      2017-04-28 [2] CRAN (R 3.5.0)                
#>  knitr         1.22       2019-03-08 [2] CRAN (R 3.5.2)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.2)                
#>  memoise       1.1.0      2017-04-21 [2] CRAN (R 3.5.0)                
#>  pkgbuild      1.0.2      2018-10-16 [2] CRAN (R 3.5.1)                
#>  pkgload       1.0.2      2018-10-29 [2] CRAN (R 3.5.1)                
#>  prettyunits   1.0.2      2015-07-13 [2] CRAN (R 3.5.0)                
#>  processx      3.3.0      2019-03-10 [2] CRAN (R 3.5.3)                
#>  ps            1.3.0      2018-12-21 [2] CRAN (R 3.5.2)                
#>  R6            2.4.0      2019-02-14 [1] standard (@2.4.0)             
#>  Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                
#>  remotes       2.0.2.9000 2019-03-21 [1] Github (r-lib/remotes@6212345)
#>  rlang         0.3.1      2019-01-08 [1] standard (@0.3.1)             
#>  rmarkdown     1.12       2019-03-14 [2] CRAN (R 3.5.3)                
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.3)                
#>  sessioninfo   1.1.1      2018-11-05 [2] CRAN (R 3.5.1)                
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                
#>  stringr       1.4.0      2019-02-10 [1] standard (@1.4.0)             
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.2)                
#>  usethis       1.4.0      2018-08-14 [2] CRAN (R 3.5.1)                
#>  withr         2.1.2      2018-03-15 [2] CRAN (R 3.5.0)                
#>  xfun          0.5        2019-02-20 [2] CRAN (R 3.5.2)                
#>  yaml          2.2.0      2018-07-25 [2] CRAN (R 3.5.1)                
#> 
#> [1] /usr/local/lib/R/site-library
#> [2] /usr/lib/R/site-library
#> [3] /usr/lib/R/library
```

</details>

**Comment by Robinlovelace** [comment] 2019-03-21 07:37
traceback:

```
9: stop(simpleError(msg, call = sys.call(-1)))
8: stopifnot(is.remote(remote))
7: FUN(X[[i]], ...)
6: vapply(remotes, install_remote, ..., FUN.VALUE = character(1))
5: install_remotes(object$remote[!object$is_cran & behind], dependencies = dependencies, 
       upgrade = upgrade, force = force, quiet = quiet, build = build, 
       build_opts = build_opts, repos = repos, type = type, ...)
4: update.package_deps(packages, dependencies = dep_deps, quiet = quiet, 
       upgrade = upgrade, build = build, build_opts = build_opts, 
       ...)
3: update(packages, dependencies = dep_deps, quiet = quiet, upgrade = upgrade, 
       build = build, build_opts = build_opts, ...)
2: remotes::install_deps(pkg$path, build = build, build_opts = build_opts, 
       INSTALL_opts = opts, dependencies = dependencies, quiet = quiet, 
       force = force, upgrade = upgrade, ...)
1: devtools::install()
```

**Comment by jimhester** [comment] 2020-07-10 15:32
I cannot reproduce the error. Most likely errors like this come from a incompatibility in the remotes specification of an installed package in your library and what remotes is expecting. The package in question will be one of the (recursive) dependencies of the package you are trying to install.

One workaround is to remove all recursive dependencies of the package in question and reinstall them from scratch.

In any case I don't think there is anything we can change in remotes to fix this issue, so I will close this.

**Closed by jimhester** 2020-07-10 15:32 UTC
Labels: bug

**Comment by Robinlovelace** [comment] 2020-07-10 15:53
Thanks for the response, I suspect you're right and am trying the command that failed now.

**Comment by Robinlovelace** [comment] 2020-07-10 15:55
Confirmed, must have been a momentary version incompatibility. Apologies.
