### ISSUE TITLE
remotes::install_deps(dependencies = TRUE) does not work well

### ISSUE THREAD

**Issue by ShixiangWang** [r-lib/remotes#458] opened 2019-11-26 06:55 UTC
Dear developer,

I found the `install_deps` function does not work well.

The `GenomeInfoDb` is a dependency for `BSgenome.Hsapiens.UCSC.hg19` package, but the former is downloaded after the latter package.

```
* installing *source* package 'BSgenome.Hsapiens.UCSC.hg19' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
##[error]Error: package or namespace load failed for 'GenomeInfoDb' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
ERROR: lazy loading failed for package 'BSgenome.Hsapiens.UCSC.hg19'
* removing 'd:/a/_temp/Library/BSgenome.Hsapiens.UCSC.hg19'
 there is no package called 'GenomeInfoDbData'
##[error]Error: package 'GenomeInfoDb' could not be loaded
Execution halted
* installing *source* package 'prettydoc' ...
** package 'prettydoc' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'prettydoc'
    finding HTML links ... done
    html_pretty                             html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (prettydoc)
* installing *source* package 'GenomeInfoDbData' ...
** using staged installation
```

```
trying URL 'https://bioconductor.org/packages/3.9/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg19_1.4.0.tar.gz'
Content type 'application/x-gzip' length 688190187 bytes (656.3 MB)
==================================================
downloaded 656.3 MB

trying URL 'https://cloud.r-project.org/src/contrib/prettydoc_0.3.1.tar.gz'
Content type 'application/x-gzip' length 966494 bytes (943 KB)
==================================================
downloaded 943 KB

trying URL 'https://bioconductor.org/packages/3.9/data/annotation/src/contrib/GenomeInfoDbData_1.2.1.tar.gz'
Content type 'application/x-gzip' length 9792100 bytes (9.3 MB)
==================================================
downloaded 9.3 MB

```

[Check details](https://github.com/ShixiangWang/sigminer/commit/522cd2f46dc4bb0f5b7616ac010214efd2c1bfa4/checks?check_suite_id=328859652#step:8:1291)

Any suggestion?

Best,
Shixiang

**Comment by jimhester** [comment] 2019-11-26 13:17
This is a duplicate of #301

**Closed by jimhester** 2019-11-26 13:17 UTC
